/**
 * PostgreSQL schema (spec §6.1 / §6.2).
 *
 * The first-version persistence model keeps each project as a full `GanttlyFile`
 * JSONB aggregate (spec §5.1). `summary_jsonb` is a query projection computed
 * inside the same transaction as `file_jsonb` — it is never a second source of
 * truth. IDs are prefixed nanoids generated by the application; the database
 * never relies on guessability for security (every query still checks workspace
 * membership).
 *
 * PR2 ships the six core tables: users, workspaces, workspace_members,
 * projects, project_operations, outbox_events. PAT and external_references
 * arrive in later PRs.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  bigserial,
  check,
  index,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

const tstz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

// ---------------------------------------------------------------------------
// users — identity, keyed by (provider, subject) so future OIDC issuers are a
// non-breaking change (spec §0 decision 3 / §6.1).
// ---------------------------------------------------------------------------
export const users = pgTable(
  'users',
  {
    id: text('id').primaryKey(),
    provider: text('provider').notNull(),
    subject: text('subject').notNull(),
    email: text('email'),
    displayName: text('display_name'),
    createdAt: tstz('created_at').notNull(),
    updatedAt: tstz('updated_at').notNull(),
  },
  (t) => ({
    providerSubjectUnique: unique('users_provider_subject_unique').on(t.provider, t.subject),
  }),
);

// ---------------------------------------------------------------------------
// workspaces
// ---------------------------------------------------------------------------
export const workspaces = pgTable(
  'workspaces',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    kind: text('kind').notNull(),
    createdBy: text('created_by')
      .notNull()
      .references(() => users.id),
    createdAt: tstz('created_at').notNull(),
    updatedAt: tstz('updated_at').notNull(),
  },
  (t) => ({
    kindCheck: check('workspaces_kind_check', sql`${t.kind} in ('personal', 'team')`),
  }),
);

// ---------------------------------------------------------------------------
// workspace_members
// ---------------------------------------------------------------------------
export const workspaceMembers = pgTable(
  'workspace_members',
  {
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    userId: text('user_id')
      .notNull()
      .references(() => users.id),
    role: text('role').notNull(),
    createdAt: tstz('created_at').notNull(),
  },
  (t) => ({
    pk: primaryKey({ name: 'workspace_members_pkey', columns: [t.workspaceId, t.userId] }),
    roleCheck: check(
      'workspace_members_role_check',
      sql`${t.role} in ('owner', 'admin', 'editor', 'viewer')`,
    ),
  }),
);

// ---------------------------------------------------------------------------
// projects — one row per project document; full GanttlyFile in file_jsonb.
// ---------------------------------------------------------------------------
export const projects = pgTable(
  'projects',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id')
      .notNull()
      .references(() => workspaces.id),
    name: text('name').notNull(),
    fileJsonb: jsonb('file_jsonb').notNull(),
    summaryJsonb: jsonb('summary_jsonb').notNull(),
    revision: bigint('revision', { mode: 'number' }).notNull().default(1),
    sourceType: text('source_type'),
    sourceClientId: text('source_client_id'),
    createdBy: text('created_by')
      .notNull()
      .references(() => users.id),
    createdAt: tstz('created_at').notNull(),
    updatedAt: tstz('updated_at').notNull(),
    deletedAt: tstz('deleted_at'),
  },
  (t) => ({
    // §6.2: project list ordering — active first, then most-recently updated.
    workspaceListIdx: index('projects_workspace_list_idx').on(
      t.workspaceId,
      t.deletedAt,
      t.updatedAt.desc(),
    ),
    // §6.2: case-insensitive name lookup within a workspace.
    workspaceNameIdx: index('projects_workspace_name_idx').on(t.workspaceId, sql`lower(${t.name})`),
  }),
);

// ---------------------------------------------------------------------------
// project_operations — audit + idempotency log (spec §6.4 / §7.3). Deliberately
// no FK to projects so operations survive project deletion for audit.
// ---------------------------------------------------------------------------
export const projectOperations = pgTable(
  'project_operations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id').notNull(),
    projectId: text('project_id').notNull(),
    actorType: text('actor_type').notNull(),
    actorId: text('actor_id').notNull(),
    action: text('action').notNull(),
    requestHash: text('request_hash'),
    idempotencyKey: text('idempotency_key'),
    expectedRevision: bigint('expected_revision', { mode: 'number' }),
    resultRevision: bigint('result_revision', { mode: 'number' }).notNull(),
    summaryJsonb: jsonb('summary_jsonb').notNull(),
    responseJsonb: jsonb('response_jsonb'),
    requestId: text('request_id').notNull(),
    createdAt: tstz('created_at').notNull(),
  },
  (t) => ({
    actorTypeCheck: check(
      'project_operations_actor_type_check',
      sql`${t.actorType} in ('web', 'mcp', 'system')`,
    ),
    // §6.2: operation history per project, newest first.
    projectCreatedIdx: index('project_operations_project_created_idx').on(
      t.projectId,
      t.createdAt.desc(),
    ),
    // §6.2 / §6.4: idempotency uniqueness scoped to (workspace, actor, key),
    // only enforced when a key is present.
    idempotencyUnique: uniqueIndex('project_operations_idempotency_unique')
      .on(t.workspaceId, t.actorType, t.actorId, t.idempotencyKey)
      .where(sql`${t.idempotencyKey} is not null`),
  }),
);

// ---------------------------------------------------------------------------
// outbox_events — transactional outbox feeding SSE (spec §11.2). `sequence` is
// a global, gap-free ordering; `published_at` null means "not yet emitted".
// ---------------------------------------------------------------------------
export const outboxEvents = pgTable(
  'outbox_events',
  {
    sequence: bigserial('sequence', { mode: 'number' }).primaryKey(),
    id: text('id').unique().notNull(),
    workspaceId: text('workspace_id').notNull(),
    projectId: text('project_id'),
    type: text('type').notNull(),
    payloadJsonb: jsonb('payload_jsonb').notNull(),
    createdAt: tstz('created_at').notNull(),
    publishedAt: tstz('published_at'),
  },
  (t) => ({
    // §6.2: fan-out scan within a workspace in sequence order.
    workspaceSequenceIdx: index('outbox_events_workspace_sequence_idx').on(
      t.workspaceId,
      t.sequence,
    ),
    // §6.2: publisher scan of unpublished events.
    publishIdx: index('outbox_events_publish_idx').on(t.publishedAt, t.sequence),
  }),
);

/** All tables, for the Drizzle client `schema` map and tests. */
export const schema = {
  users,
  workspaces,
  workspaceMembers,
  projects,
  projectOperations,
  outboxEvents,
};
